### PR TITLE
update guides for linux/pi

### PR DESCRIPTION
**Pull request by christhechris**
Expand guide and generalise to Ubuntu and Raspi OS Linux.

### CODE REVIEW

**Comment by YiweiMao** [comment]
This is looking very good. 
I'll make some minor changes adding that Jetsons are also a viable platform (although I don't have one for testing) and edit our custom sidebar so the change to the notebook name is linked correctly in the docs site.

**Comment by christhechris** [comment]
No worries. I thought I got the side bar modified, but may have missed something.

**Comment by YiweiMao** [comment]
Looks like the sidebar got auto updated this time (it didn't before!)
I went ahead and added some Ximea install details and a FAQ section to index.ipynb

**Review by YiweiMao — APPROVED** [review]
BTW, the current github pages is sourced from this branch now. Just so I can check if it deployed fine. 
Nice work with this new tutorial!

**Comment by christhechris** [comment]
> Looks like the sidebar got auto updated this time (it didn't before!)
> I went ahead and added some Ximea install details and a FAQ section to index.ipynb

Looks good. We can prob skip pull request review etc for updating that. Other option is to link to another page, say GitHub wiki, and then update to main docs less often.

**Comment by YiweiMao** [comment]
Yeah, I wanted you to have a chance to review my changes before merging into master. I think for minor docs changes from now on, we can skip review and just merge them in. Leaving review for major docs changes and new code.

**Pull request merged**
