### PR TITLE
Fix for mkdir issue and updated jupyterlab in install guide

### PR DESCRIPTION
**Pull request by YiweiMao**
More verbose docs in data module. 

Do you think we should release version 0.2.3 with this fix?
It's just `make release` right?

### CODE REVIEW

**Comment by christhechris** [comment]
Yup. Just do pypi, conda auto builds off that now. (Via cobda-forge)

**Comment by YiweiMao** [comment]
I see there's a conda-forge version. 
image
Is this the definitive source now? Which will need to be updated in our Readme. 
image

**Comment by christhechris** [comment]
Was Keeping both up to-date, but yeah pref the forge version.

**Comment by YiweiMao** [comment]
Ok. It looks like the makefile recipe doesn't update the conda description from our readme
https://anaconda.org/conda-forge/openhsi

**Comment by christhechris** [comment]
No, I did manually last time, but i think not super critical tbh.
Stuff is on repo and and docs page.

**Comment by YiweiMao** [comment]
I'm having some trouble making the conda package
FileNotFoundError: [Errno 2] No such file or directory: 'conda' 
even though the makefile makes the conda directory. I'll need to diagnose this later. 
Looks like I might need Anaconda Python to proceed.

**Comment by christhechris** [comment]
No worries. I csn sort for now.

**Comment by christhechris** [comment]
which commit is v0.2.3 (just want to tag it)?

**Comment by YiweiMao** [comment]
It was the one before I fixed a typo. 
Currently trying to fix the issue I linked at the moment (this is just updating docs links so nothing to do with the library code)

**Pull request merged**
